### ISSUE TITLE
Scroll inside bottom sheet

### ISSUE THREAD

**Issue by vadimwe** [CarboniDavide/ion-bottom-sheet#1]
Hi, thank you for great job! 👍

How about scroll inside bottom sheet? Is it possible?
And it will be great to have possibility to change close button.

**Comment by CarboniDavide** [comment]
Hi, scroll inside is possible of course, I will do it probably in the next release, but I'm not sure!

To Change close button you have to modify or change SVG content directly using **#close-button** ID inside CSS style.

**Comment by vadimwe** [comment]
Any update?

**Comment by Saqib92** [comment]
Update?

**Comment by CarboniDavide** [comment]
Scroll is now available
