### ISSUE TITLE
Not Working in Latest Ionic Version.

### ISSUE THREAD

**Issue by Saqib92** [CarboniDavide/ion-bottom-sheet#2]
Showing Errors in Latest Ionic Version. 

`Can't bind to 'state' since it isn't a known property of 'ion-bottom-sheet'.`
`Can't bind to 'minHeight' since it isn't a known property of 'ion-bottom-sheet'.`

Ionic Details Are as Below: 
```
Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\najamussaqib\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.0
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : 1.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\najamussaqib\AppData\Local\Android\Sdk)
   NodeJS            : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.6
   OS                : Windows 10
```

P.S: Working Example Repository will be a Big Plus 👍 Thanks for this Library.

**Comment by CarboniDavide** [comment]
This is an error of import and not a bug!

Try to import **IonBottomSheetModule** in the right Module.

For example if you are using module in your HomePageModule you need to declare it in your **imports** section:

    import { IonBottomSheetModule } from 'ion-bottom-sheet';
    
    @NgModule({
      imports: [
        CommonModule,
        FormsModule,
        IonicModule,
        HomePageRoutingModule,
        IonBottomSheetModule
      ],
      declarations: [HomePage]
    })
    export class HomePageModule {}
