### ISSUE TITLE
Is it possible to call a function whenever the SheetState is changed?

### ISSUE THREAD

**Issue by elco45** [CarboniDavide/ion-bottom-sheet#6]
Is there any way or plan to integrate the possibility of calling a function whenever the sheet state is changed? 
onSheetBottom, onSheetTop, onSheetDocked

Ex)
<ion-bottom-sheet
    [(state)]="sheetState"
    [onSheetBottom]="someFunction($event)"
  >

**Comment by CarboniDavide** [comment]
Yes of course. Use **sheetState** Event as:

<ion-bottom-sheet (sheetState)="myFunction()">
</ion-bottom-sheet>

**Comment by CarboniDavide** [comment]
Yes of course. Use **stateChange** Event.

For example:

```html
<ion-bottom-sheet 
  (stateChange)="onStateChange($state)" 
>
</ion-bottom-sheet>
```

and in your component:

```typescript
onStateChange(state){
    console.log(state);
  }
```

> stateChange Event is fired **only** in children component
