### ISSUE TITLE
Is it possible to disable drag when I change a variable from the children?

### ISSUE THREAD

**Issue by elco99** [CarboniDavide/ion-bottom-sheet#7]
I have an ion-slides inside the ion-bottom-sheet and I want to prevent the sheet from being dragged when I'm moving through the slides. To do so, I'm trying to manage a variable that will be changed whenever I start touching the slides.

Ex)
```
// example.ts
disDrag = false
...
slideTouchStart() {
   this.disDrag = true;
}
slideTouchEnd() {
   this.disDrag = false;
}
...

// example.html
<ion-bottom-sheet
   ....
    [disableDrag]="disDrag"
>
   <ion-slides
      ...
      (ionSlideTouchStart)="slideTouchStart()"
      (ionSlideTouchEnd)="slideTouchEnd()"
    >
        ....
  </ion-slides>
</ion-bottom-sheet>
```

I can see that my variable disDrag is changing, however, the dragging is still occurring. Is there a way for me to prevent the scrolling when I start touching the children ion-slides?

**Comment by CarboniDavide** [comment]
I'm sorry, but this is currently not possible.

Currently, the only input processed after the component is loaded is the **state**. 

Being able to disable scrolling in runtime would be a good idea. Right now, i don't think i will include this possibility in a next release.

In any case, as you well know, I encourage you to download the component to customize it according to your needs.
