### ISSUE TITLE
Is Ion-bottom-Sheet is available in react js?

### ISSUE THREAD

**Issue by vairamuthu16** [CarboniDavide/ion-bottom-sheet#8]
I'm working in a react typescript project,for that I need to use bottom sheet. Is Ion Bottom Sheet is Available in react version as i seen there is only in angular version I need your help to complete my project, if bottom sheet feature is available in react kindly share the documentation and demos link 

Regards 
Vairamuthu R

**Comment by CarboniDavide** [comment]
Dear Vairamuthu,
actually there is no a version of the project in react.

Regards
